title: The Role of Inclusive Language in Technical Writing
description: A guide to understanding and implementing inclusive language in technical communication and beyond.
theme: just-the-docs

url: https://majaborgosz.github.io/inclusivelanguage
aux_links: 
  Project Repository: https://github.com/majaborgosz/inclusivelanguage
color_scheme: colorscheme
favicon: /images/favicon.svg
