title: The Role of Inclusive Language in Technical Writing
description: A guide to understanding and implementing inclusive language in technical communication and beyond.
theme: just-the-docs

url: https://majaborgosz.github.io/inclusivelanguage
aux_links: 
  Project Repository: https://github.com/majaborgosz/inclusivelanguage
  footer_content: "&#169; Maja Borgosz (Solik), 2025"
color_scheme: colorscheme
back_to_top: true
back_to_top_text: "Back to top"
heading_anchors: true

//logo 
//favicon-ico
