title: The Role of Inclusive Language in Technical Writing
description: The Role of Inclusive Language in Technical Writing
theme: just-the-docs

url: https://majaborgosz.github.io/inclusivelanguage
color_scheme: colorscheme
aux_links: 
  Project Repository: https://github.com/majaborgosz/inclusivelanguage
