title: The Role of Inclusive Language in Technical Writing
description: The Role of Inclusive Language in Technical Writing
theme: just-the-docs

url: https://majaborgosz.github.io/inclusivelanguage

aux_links: 
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
